### PR TITLE
repo: Add licensing documents, copyright headers to files

### PR DESCRIPTION
**Pull request by cmoussa1**
As mentioned in #3, none of the files in the repository contain a Copyright header:

```
###############################################################
# Copyright 2014 Lawrence Livermore National Security, LLC
# (c.f. AUTHORS, NOTICE.LLNS, COPYING
...
```

This PR adds the header to all of the source files in the repo, as well as adds the licensing documents and appropriate symlinks to the repository.

### CODE REVIEW

**Comment by chu11** [comment]
LGTM, although maybe we should update copyright year to 2020?  I'm not 100% sure about this.  I normally update ... but that's me.  Other opinions?

**Comment by garlick** [comment]
The copyright year in a source file should be the year the source was initially created IMHO.  Then leave it alone unless you think it will be relevant longer than mickey mouse!

https://alj.artrepreneur.com/mickey-mouse-keeps-changing-copyright-law/

**Comment by cmoussa1** [comment]
Thanks for the clarification on this! I was wondering about it myself. Just pushed an update to edit the Copyright year to 2020.

**Comment by chu11** [comment]
LGTM, if you are ready I can hit the button.

**Comment by cmoussa1** [comment]
Ready!

**Pull request merged**
