### PR TITLE
`view-job-records`: add `--project` filter option

### PR DESCRIPTION
**Pull request by cmoussa1**
#### Problem

There is no way to filter jobs by project when looking at job records in flux-accounting's `jobs` table. This could be a useful feature now that the priority plugin validates and annotates project names for jobs.

---

This PR adds a `project` column to the `jobs` table that can store an optional project name for each job. It then adds an optional argument to the `view-job-records` command `--project` which can filter jobs by project name:

```console
flux account view-job-records --project=projectA
```

I've updated some existing tests that use the `view-job-records` command as well as added a new test file that tests filtering jobs by project name.

### CODE REVIEW

**Comment by cmoussa1** [comment]
@ryanday36 would you like to give this PR a high-level look and let me know if this might be a useful feature? I thought this might be a first-crack at tackling #352 to make it easier to gather jobs by project.

**Comment by ryanday36** [comment]
This definitely looks useful! Thanks @cmoussa1

**Review by jameshcorbett — APPROVED** [review]
LGTM!

**Comment by cmoussa1** [comment]
Thanks @jameshcorbett! Setting MWP here

**Pull request merged**
