### PR TITLE
repo: remove unused imports, variable in accounting/, change license in fairness/ to LGPL

### LINKED ISSUE #83: repo: clean up unused 'import' statements
A series of files in `src/bindings/python/flux/accounting/` have unused `import` statements in them, as revealed by `flake8`:

**accounting_cli_functions.py**

```
accounting_cli_functions.py:14:1: F401 'pwd' imported but unused
accounting_cli_functions.py:15:1: F401 'csv' imported but unused
```

**create_db.py**

```
create_db.py:13:1: F401 'pandas as pd' imported but unused
create_db.py:15:1: F401 'argparse' imported but unused
```

**job_archive_interface.py**

```
job_archive_interface.py:12:1: F401 'sqlite3' imported but unused
job_archive_interface.py:16:1: F401 'os' imported but unused
```

**print_hierarchy.py**

```
print_hierarchy.py:12:1: F401 'sqlite3' imported but unused
```

### PR DESCRIPTION
**Pull request by cmoussa1**
**Problem(s)**: 

- `flake8` revealed a number of unused `import` statements throughout `src/bindings/python/flux/accounting/`.

- The headers in `fairness/` are marked as GPL, but the repo is licensed LGPL.

---

This PR removes the unused `import` statements (as well as an unused variable in **job_archive_interface.py**) as well as changes the headers in `fairness/` to LGPL. I simply copied the license header from `src/fairness/print_hierarchy/print_hierarchy.cpp`.

I'm not sure if we want to squash down the four commits that remove the `import` statements into one larger commit, but for now I just left them as separate commits. 

Fixes #83, #66

### CODE REVIEW

**Comment by dongahn** [comment]
Thank you for changing the copy right header for weight tree lib code! Because the new header points to LICENSE and NOTICE.LLNS

you may as well pull in the following from flux-core

https://github.com/flux-framework/flux-core/blob/master/LICENSE
https://github.com/flux-framework/flux-core/blob/master/NOTICE.LLNS

**Comment by cmoussa1** [comment]
Thanks for pointing that out @dongahn! I went ahead and moved `COPYING` to `LICENSE` to mirror flux-core. I believe flux-accounting has the same `NOTICE.LLNS` file that you referenced, however:

https://github.com/flux-framework/flux-accounting/blob/master/NOTICE.LLNS

Let me know if this isn't what you meant.

**Review by SteVwonder — APPROVED** [review]
Thanks @cmoussa1! LGTM!

**Comment by cmoussa1** [comment]
Thanks @SteVwonder! Setting MWP...

**Pull request merged**
