### PR TITLE
NEWS.md: add release notes for v0.6.0

### LINKED ISSUE #99: flux-accounting: create release for v0.6.0
Will need to update **NEWS.md** with some of the new features and bug fixes, which can be pulled from the January milestone.

### PR DESCRIPTION
**Pull request by cmoussa1**
_note: I will leave this as a draft in case #91 and #97 can get approved and landed by the end of the month._

Add Release Notes for v0.6.0.

Fixes #99

### CODE REVIEW

**Comment by dongahn** [comment]
@cmoussa1: this looks good to me. Once the other PR is landed, feel free to put MWP to merge it. Thanks.

**Comment by cmoussa1** [comment]
Thanks again for approving this! I'll go ahead and set MWP.

**Comment by cmoussa1** [comment]
Hm. I wonder why this hasn't been merged yet. Does it need an "official" approval on GitHub before it can get merged? @SteVwonder

**Comment by dongahn** [comment]
Yes I think you need at least one approval, I think. Let me add one.

**Review by dongahn — APPROVED** [review]
LGTM!

**Pull request merged**
