### PR TITLE
database: add queue_table, subcommands for interacting with queue_table

### LINKED ISSUE #164: database: define and configure queue limit information
A result from some of the discussion in flux-framework/flux-sched#839 was the need to support per-queue limits. To make some concrete progress to tackle this front, flux-accounting should be able to support defining and configuring basic queue limit information. This can most likely be done by creating a table in the database with a series of columns that describe the various limits that are enforced for a given queue. 

So far, the limits we should be able to define and configure are:

- minimum nodes per job
- maximum nodes per job
- max time per job

### PR DESCRIPTION
**Pull request by cmoussa1**
#### Problem

As discussed in #164, there is a need for being able to define and configure queue information within the flux-accounting database.

---

#### Solution

This is a [WIP] PR that I just wanted to post before the Thanksgiving break that adds such support within the DB. It adds a new table, `queue_table`, which holds just 4 columns - the name of the queue and a couple of required limits associated with each queue:

```
queue               tinytext        NOT NULL,
min_nodes_per_job   int(11),
max_nodes_per_job   int(11),
max_time_per_job    int(11),
PRIMARY KEY (queue)
```

_Note that the only column that is required when adding a new queue is the name; if not specified, all of the limit columns could just be empty, with no default values._

Support for interacting with this table from the command line with a number of subcommands added to `flux account`: `add-queue`, `view-queue`, `delete-queue`, and `edit_queue`. These functions allow a DB admin to add, edit, remove, and view queue information to the flux-accounting DB.

#### Usage

```console
[moussa1@docker-desktop src]$ flux account add-queue -h
positional arguments:
  QUEUE                 queue name

optional arguments:
  -h, --help            show this help message and exit
  --min-nodes-per-job MIN NODES PER JOB    min nodes per job
  --max-nodes-per-job MAX NODES PER JOB    max nodes per job
  --max-time-per-job  MAX TIME PER JOB     max time per job
```

```console
[moussa1@docker-desktop src]$ flux account view-queue -h
positional arguments:
  QUEUE       queue name

optional arguments:
  -h, --help  show this help message and exit
```

```console
[moussa1@docker-desktop src]$ flux account edit-queue -h
optional arguments:
  -h, --help         show this help message and exit
  --queue queue      queue name
  --field FIELD      column name
  --new-value VALUE  new value
```

```console
[moussa1@docker-desktop src]$ flux account delete-queue -h
positional arguments:
  QUEUE       queue name

optional arguments:
  -h, --help  show this help message and exit
```
Both unit tests and sharness tests were added with the new subcommands and module.

Fixes #164

### CODE REVIEW

**Comment by cmoussa1** [comment]
OK, I think this might be ready for a review now. @ryanday36 if you have some time, could you give this a look? I figured you might be a good person to tag for a review since you might be the one responsible for managing queues in the DB. 🙂

**Comment by ryanday36** [comment]
Hey @cmoussa1, this looks pretty good. The one thought that I have from a usability standpoint would be to have the edit-queue command take the same arguments as the add-queue command. e.g. `--min-nodes-per-job 10 pbatch` instead of `--field min-nodes-per-job --value 10 --queue pbatch`. This might just be a matter of documentation, but the other thing that I'd like to see on the edit-queue command would be the ability to remove a limit. That could come down to just setting something along the lines of `--value ''` or `--value -1` with the edit-queue command or be a new argument.

**Comment by cmoussa1** [comment]
Thanks for this great feedback @ryanday36! I went ahead and refactored the `edit-queue` subcommand to take a `queue` positional argument and optional arguments for all of the limits.

```console
[moussa1@docker-desktop src]$ flux account edit-queue -h
usage: flux-account.py edit-queue [-h] [--min-nodes-per-job MIN NODES PER JOB]
                                  [--max-nodes-per-job MAX NODES PER JOB]
                                  [--max-time-per-job MAX TIME PER JOB]
                                  QUEUE
```

So now a queue's limit (or multiple limits at the same time) can be edited with the following:

```console
$ flux account edit-queue queue_1 --max-nodes-per-job 100
```

You can also reset a limit by passing `-1` to the limit you want to reset.

```console
sudo flux account edit-queue queue_1 --max-nodes-per-job -1
```

Let me know what you think of these changes.

**Review by ryanday36 — APPROVED** [review]
Nice! Looks good to me.

**Comment by cmoussa1** [comment]
Woo! Thanks. I'll set MWP

**Pull request merged**
