### PR TITLE
add flux-accounting v0.2.0 release notes

### PR DESCRIPTION
**Pull request by cmoussa1**
This PR adds the release notes for flux-accounting v0.2.0. This PR should go in after #33, #34, and #36 land.

### CODE REVIEW

**Comment by dongahn** [comment]
@cmoussa1: I sent you an email but let's chat by phone to see what we should do to land all of your 4 pending PRs.

**Comment by cmoussa1** [comment]
I'll go ahead and drop the **[WIP]** tag, but like I mentioned above I don't think this should land until #34 and #36 land.

**Comment by dongahn** [comment]
OK. This looks good to me too. Adding MWP. Once this is merged you can add your tag! Great work @cmoussa1!

**Comment by dongahn** [comment]
@Mergifyio rebase

**Comment by cmoussa1** [comment]
Woo! Thanks @dongahn 🎉

**Comment by dongahn** [comment]
@cmoussa1: BTW, we don't have Travis CI set up for flux-accounting? Soon we will need to set this up -- this will be particularly important as flux-account will have dependencies to other flux projects.

**Comment by cmoussa1** [comment]
> BTW, we don't have Travis CI set up for flux-accounting? Soon we will need to set this up -- this will be particularly important as flux-account will have dependencies to other flux projects.

Not yet. I can add this as a `TODO` to flux-accounting.

**Comment by cmoussa1** [comment]
Oh yeah, @dongahn I think you'll need to "approve" this PR officially for it to be merged automatically, right?

**Review by dongahn — APPROVED** [review]

**Comment by dongahn** [comment]
Done.

**Pull request merged**
