### PR TITLE
NEWS.md: add release notes for v0.5.0

### LINKED ISSUE #85: NEWS.md: add release notes for v0.5.0

### PR DESCRIPTION
**Pull request by cmoussa1**
_note: I will leave this as a draft until #79 is approved and landed._

Add Release Notes for v0.5.0.

Fixes #85

### CODE REVIEW

**Comment by cmoussa1** [comment]
Now that #79 has landed, I'll open this up officially for review.

**Comment by cmoussa1** [comment]
Rebased to catch up after #79.

**Review by SteVwonder — APPROVED** [review]
LGTM! Thanks @cmoussa1!

**Comment by dongahn** [comment]
Congrats Chris for this release! And of course big thanks to @SteVwonder! This is an excellent foundation to build on towards integrating flux-accounting to the rest of Flux!

**Comment by cmoussa1** [comment]
Couldn't have done it without you guys! :-)

**Pull request merged**
