### PR TITLE
database: add `project_table`, `projects` column to association_table

### LINKED ISSUE #253: flux-accounting DB: add "project" column, "project" table
Probably the first sub-issue to open as a result of #247 is to add support in the flux-accounting database to store "projects" for each user/bank row in the `association_table`, as well as a "projects" table to store names of projects. A quick schema comes to mind for both the row and the table itself:

```sql
project    tinytext    DEFAULT '*'    NOT NULL
```

```sql
CREATE TABLE IF NOT EXISTS projects_table (
    project_id    integer    PRIMARY KEY    AUTOINCREMENT,
    project       text                      NOT NULL
);
```

We can then add support in the `add-user` and `edit-user` commands to specify projects when adding a user/bank row for the first time as well as editing eligible projects for a user/bank row after they've been added.

Separate commands should probably also be added to add, remove, view, and edit projects in the `projects_table`. (side note: the fixes introduced in PR #252 should hopefully alleviate the issues we've run into in the past with updating our currently-installed DB's on fluke, so adding this will be a good test to ensure the `update-db` command is working as expected :P).

### PR DESCRIPTION
**Pull request by cmoussa1**
As discussed in #247 and in #253, there is need to support projects within flux-accounting, or the ability for multiple users from different banks to all work on the same project. One of the first requirements is to be able to add projects to a table to keep track of as well as list projects that a user belongs to in the `association_table`.

---

This is a [WIP] PR that adds a new table to the flux-accounting database: `project_table`, a table storing project names. Its schema consists of the following:

```sql
CREATE TABLE IF NOT EXISTS project_table (
        project_id          integer    PRIMARY KEY AUTOINCREMENT,
        project             tinytext               NOT NULL
);
```

A new column is also added to the `association_table`: `projects`, which stores all of the projects that a user is allowed to specify when running jobs. A default value (`*`) is added as a default project for all users when they are added to the flux-accounting DB:

```sql
projects         tinytext    DEFAULT '*'            NOT NULL    ON CONFLICT REPLACE DEFAULT '*'
```

A couple of new commands to interact with the `project_table` are also added that allows an admin to add, view, and remove project information from the table. A helper function is also added to the `add-user` and `edit-user` commands to validate the projects specified for a user/bank row in the `association_table` so that a user does not get added to a project that does not exist in the `project_table`.

When removing a project from the `project_table`, a quick check is performed in the `association_table` to see if any user/bank rows still reference this project; if so, a warning message is printed notifying the admin that the project being deleted is still being referenced, and thus those user rows should be edited to account for the deletion. 

Both unit tests and sharness tests are added to test both the functions that interact with the `project_table` and the `add-project`, `view-project`, and `delete-project` commands.

Since I am still a little unfamiliar with our current use of projects (currently known as WCKeys), I'll pose a couple questions here that might help add some more useful functionality or change my current PR to be better:

- are deleting projects common on our current machines? When projects get deleted, do any users who still reference that project also get edited automatically to no longer reference that project, or are admins also responsible for changing those user rows?
- do projects have a `job_usage` value? i.e is it common on our current machines to calculate a usage value for all of the jobs that run under a specific project? I know @ryanday36 mentioned in #247 that it does not affect and is not included in fairshare, but I figured I could get a little more clarification in case I should add another column to the `project_table` to include a usage value.

Fixes #253

### CODE REVIEW

**Comment by ryanday36** [comment]
regarding deleting projects: I think it's okay to require the admin to remove projects from a user before deleting them. That said, an easy tool to do this would no doubt be welcome.

regarding usage: We will want to be able to calculate the total usage for all of the jobs that use a given project in a given time frame, but that's different than the usage that is used for fairshare (which has the half-life decay applied to it). As long as jobs are tagged with a project, we can calculate the usage when needed.

Does this PR include a means of specifying a default project for a user. e.g. if a user has multiple projects, can one be specified as the one to be used if the user doesn't specify a project when they submit their job?

**Comment by cmoussa1** [comment]
> regarding deleting projects: I think it's okay to require the admin to remove projects from a user before deleting them. That said, an easy tool to do this would no doubt be welcome.

Sounds good. Perhaps if it's okay with you, and to keep this PR relatively simple, maybe I can add such a tool in a subsequent PR shortly after this one lands?

> regarding usage: We will want to be able to calculate the total usage for all of the jobs that use a given project in a given time frame, but that's different than the usage that is used for fairshare (which has the half-life decay applied to it). As long as jobs are tagged with a project, we can calculate the usage when needed.

OK, this sounds good. So maybe I should add in fact a `usage` column to the `project_table`; the difference between a project's job usage and a user's job usage is that the project's usage does not have a half-life decay applied to it?  

This means, in the job usage calculation script in this repository (and in the `flux account update-usage` command), perhaps an additional optional argument should be added that allows an admin to query all jobs that ran under a specific project. I think I can accomplish this now if a user sets a project similar to how they currently specify a bank (with `--setattr=system.project=my_project`). Then, we can probably query jobs from the job-archive database in flux-core by only appending jobs that contain a specific project in jobspec. This functionality would probably also be best suited as a subsequent PR.

> Does this PR include a means of specifying a default project for a user. e.g. if a user has multiple projects, can one be specified as the one to be used if the user doesn't specify a project when they submit their job?

Yes, this PR does add a default project for every user who is added to the flux-accounting database - the default project name for a user is just an asterisk (`*`), which I _think_ is what we currently use on our systems? Please let me know if this is incorrect (or if you have a suggestion for a better default name). So a user should not have to specify a project when they run jobs, and if they belong to multiple projects, not specifying a project name will result in running under a default project (`*`).

**Comment by ryanday36** [comment]
> > regarding deleting projects: I think it's okay to require the admin to remove projects from a user before deleting them. That said, an easy tool to do this would no doubt be welcome.
> 
> Sounds good. Perhaps if it's okay with you, and to keep this PR relatively simple, maybe I can add such a tool in a subsequent PR shortly after this one lands?
> 

Yes. That sounds good.

> > regarding usage: We will want to be able to calculate the total usage for all of the jobs that use a given project in a given time frame, but that's different than the usage that is used for fairshare (which has the half-life decay applied to it). As long as jobs are tagged with a project, we can calculate the usage when needed.
> 
> OK, this sounds good. So maybe I should add in fact a `usage` column to the `project_table`; the difference between a project's job usage and a user's job usage is that the project's usage does not have a half-life decay applied to it?
> 
> This means, in the job usage calculation script in this repository (and in the `flux account update-usage` command), perhaps an additional optional argument should be added that allows an admin to query all jobs that ran under a specific project. I think I can accomplish this now if a user sets a project similar to how they currently specify a bank (with `--setattr=system.project=my_project`). Then, we can probably query jobs from the job-archive database in flux-core by only appending jobs that contain a specific project in jobspec. This functionality would probably also be best suited as a subsequent PR.
> 

It sounds like I wasn't quite clear on this. The usage that we report for projects will have arbitrary start and end dates, so isn't really suited to keeping in the association table. We'll be calculating it from archived jobs or something along those lines. The SlurmDB does have tables where it keeps aggregated usages for associations by hour / day / month, and we may want to do something like that eventually, but it's not a near term concern for me.

> > Does this PR include a means of specifying a default project for a user. e.g. if a user has multiple projects, can one be specified as the one to be used if the user doesn't specify a project when they submit their job?
> 
> Yes, this PR does add a default project for every user who is added to the flux-accounting database - the default project name for a user is just an asterisk (`*`), which I _think_ is what we currently use on our systems? Please let me know if this is incorrect (or if you have a suggestion for a better default name). So a user should not have to specify a project when they run jobs, and if they belong to multiple projects, not specifying a project name will result in running under a default project (`*`).

If I'm understanding this correctly, it's not quite what I was looking for. What I'd like would be more like if a user belonged to 'projectA' and 'projectB', a way to say that if the user doesn't specify a project name when they submit a job, the job should get 'projectB'.

**Comment by cmoussa1** [comment]
> It sounds like I wasn't quite clear on this. The usage that we report for projects will have arbitrary start and end dates, so isn't really suited to keeping in the association table. We'll be calculating it from archived jobs or something along those lines. The SlurmDB does have tables where it keeps aggregated usages for associations by hour / day / month, and we may want to do something like that eventually, but it's not a near term concern for me.

Sorry about the confusion from my end; I think I was proposing keeping usage by project in the `project_table`, not in the `association_table`. The usage calculated for a project would be calculated by fetching jobs from flux-core's job-archive DB (where old job records are stored) and could have time filters applied to it as well (e.g "I want all of the jobs that under projectA before time X"). Does that sound more like what you were looking for?

> If I'm understanding this correctly, it's not quite what I was looking for. What I'd like would be more like if a user belonged to 'projectA' and 'projectB', a way to say that if the user doesn't specify a project name when they submit a job, the job should get 'projectB'.

Ah, okay - sorry about that. I misunderstood then! So were you thinking that a user could have a default project name, kind of like how users currently belong to banks and have a default bank?

**Comment by ryanday36** [comment]
> > It sounds like I wasn't quite clear on this. The usage that we report for projects will have arbitrary start and end dates, so isn't really suited to keeping in the association table. We'll be calculating it from archived jobs or something along those lines. The SlurmDB does have tables where it keeps aggregated usages for associations by hour / day / month, and we may want to do something like that eventually, but it's not a near term concern for me.
> 
> Sorry about the confusion from my end; I think I was proposing keeping usage by project in the `project_table`, not in the `association_table`. The usage calculated for a project would be calculated by fetching jobs from flux-core's job-archive DB (where old job records are stored) and could have time filters applied to it as well (e.g "I want all of the jobs that under projectA before time X"). Does that sound more like what you were looking for?
> 

kind of. The trick is that I don't necessarily know ahead of time what filters we would want. I think that it's usually the usage for the past quarter, but sometimes it might be the usage for two quarters ago, and others it might be just the past month. I can talk to Greg T about whether there are any common things that would be worth keeping in the project table, but I don't see that as urgent. It's more important that jobs in the job archive DB have an appropriate project associated with them.

> > If I'm understanding this correctly, it's not quite what I was looking for. What I'd like would be more like if a user belonged to 'projectA' and 'projectB', a way to say that if the user doesn't specify a project name when they submit a job, the job should get 'projectB'.
> 
> Ah, okay - sorry about that. I misunderstood then! So were you thinking that a user could have a default project name, kind of like how users currently belong to banks and have a default bank?

Yes. That would be perfect.

**Comment by cmoussa1** [comment]
> kind of. The trick is that I don't necessarily know ahead of time what filters we would want. I think that it's usually the usage for the past quarter, but sometimes it might be the usage for two quarters ago, and others it might be just the past month. I can talk to Greg T about whether there are any common things that would be worth keeping in the project table, but I don't see that as urgent. It's more important that jobs in the job archive DB have an appropriate project associated with them.

OK. I think that makes sense. Thanks for clarifying that with me. In the case of this PR, I think I will just hold off on adding the capability of associating jobs with projects (just for now) until a future PR. I think it will keep the direction of this one relatively straightforward, and in a future PR, I can start looking at how we want to add associating jobs with projects. 

>>> If I'm understanding this correctly, it's not quite what I was looking for. What I'd like would be more like if a user belonged to 'projectA' and 'projectB', a way to say that if the user doesn't specify a project name when they submit a job, the job should get 'projectB'.

>> Ah, okay - sorry about that. I misunderstood then! So were you thinking that a user could have a default project name, kind of like how users currently belong to banks and have a default bank?

> Yes. That would be perfect.

OK, cool. So I'll go ahead and edit this PR to instead treat projects (and default projects) more like banks, where users can have a default project when none is specified. Does this mean that at least one project _has_ to be specified when a user is added to the `association_table`? That would also be similar to having to specify a bank when a user is added to the `association_table` as well.

**Comment by ryanday36** [comment]
> OK, cool. So I'll go ahead and edit this PR to instead treat projects (and default projects) more like banks, where users can have a default project when none is specified. Does this mean that at least one project _has_ to be specified when a user is added to the `association_table`? That would also be similar to having to specify a bank when a user is added to the `association_table` as well.

No, we want both kinds of defaults :) If no project is specified when the user is created, giving them '*' for their project and default project is what we want.

**Comment by cmoussa1** [comment]
> No, we want both kinds of defaults :) If no project is specified when the user is created, giving them '*' for their project and default project is what we want.

Ah, okay, I think I understand. Thanks! I'll go back and rework this PR slightly to account for this behavior.

**Comment by cmoussa1** [comment]
OK, I've pushed the following changes to this PR in regards to handling default project names:

A user can be added to the `association_table` with specified projects, like so:

```console
$ flux account add-user --username=user1234 --bank=bank_A --projects="project_A,project_B,project_C"
```

`project_A` will become the user's default project (since it was the first project listed), and if no project is specified when running jobs, jobs will fall under `project_A`. A user's default project can also be edited with the `edit-user` command:

```console
$ flux account edit-user user1234 --default_project=project_B
```

If a user is added to the `association_table` without specifying any projects, a default project (`*`) is added for the user automatically, and jobs submitted without specifying a project will fall under `*`.

Every user who is added to the `association_table` belongs to the `*` project, but will only run jobs under `*` project if they do not already have another default project.

@ryanday36 - whenever you get the chance, let me know if this is the functionality you had in mind, or if there's something I missed in your explanation.

**Review by ryanday36 — COMMENTED** [review]
Looks good. Nice work @cmoussa1!

**Comment by cmoussa1** [comment]
Thanks again for reviewing @ryanday36! I'll set MWP on this

**Comment by cmoussa1** [comment]
Ah, sorry @ryanday36, I didn't realize until just now - I think you might need to explicitly "approve" this PR in order for it to be merged.

**Review by ryanday36 — APPROVED** [review]

**Comment by ryanday36** [comment]
Sorry. Forgot to click the radio button. Should be good now.

**Comment by cmoussa1** [comment]
Thanks!!

**Pull request merged**
